import { Track, QueueState, BotGuild, BotStats, VoiceChannel } from '@/types';

export const MOCK_TRACKS: Track[] = [
  {
    id: '1',
    title: 'Blinding Lights',
    author: 'The Weeknd',
    url: 'https://youtube.com/watch?v=4NRXx6U8ABQ',
    thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80',
    duration: 200,
    durationFormatted: '3:20',
    requestedBy: 'Deniz#0001',
    requestedByAvatar: 'https://i.pravatar.cc/40?img=1',
    source: 'youtube',
  },
  {
    id: '2',
    title: 'As It Was',
    author: 'Harry Styles',
    url: 'https://youtube.com/watch?v=H5v3kku4y6Q',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80',
    duration: 167,
    durationFormatted: '2:47',
    requestedBy: 'Rinz#1234',
    requestedByAvatar: 'https://i.pravatar.cc/40?img=2',
    source: 'youtube',
  },
  {
    id: '3',
    title: 'Anti-Hero',
    author: 'Taylor Swift',
    url: 'https://youtube.com/watch?v=b1kbLwvqugk',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80',
    duration: 200,
    durationFormatted: '3:20',
    requestedBy: 'Deniz#0001',
    requestedByAvatar: 'https://i.pravatar.cc/40?img=3',
    source: 'spotify',
  },
  {
    id: '4',
    title: 'Flowers',
    author: 'Miley Cyrus',
    url: 'https://youtube.com/watch?v=G7KNmW9a75Y',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80',
    duration: 200,
    durationFormatted: '3:20',
    requestedBy: 'User#5678',
    requestedByAvatar: 'https://i.pravatar.cc/40?img=4',
    source: 'youtube',
  },
  {
    id: '5',
    title: 'Unholy',
    author: 'Sam Smith & Kim Petras',
    url: 'https://youtube.com/watch?v=Uq9gPaIzbe8',
    thumbnail: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80',
    duration: 156,
    durationFormatted: '2:36',
    requestedBy: 'Rinz#1234',
    requestedByAvatar: 'https://i.pravatar.cc/40?img=5',
    source: 'soundcloud',
  },
];

export const MOCK_QUEUE_STATE: QueueState = {
  tracks: MOCK_TRACKS,
  currentIndex: 0,
  currentTrack: MOCK_TRACKS[0],
  isPlaying: true,
  isPaused: false,
  loop: 'off',
  shuffle: false,
  volume: 80,
  progress: 45,
  timestamp: Date.now(),
};

export const MOCK_GUILDS: BotGuild[] = [
  {
    id: '123456789012345678',
    name: 'DENZZMUSIC Official',
    icon: null,
    memberCount: 1247,
    botPresent: true,
    voiceChannel: '987654321098765432',
    voiceChannelName: '🎵 Music Lounge',
    mode247: true,
    isPlaying: true,
    currentTrack: MOCK_TRACKS[0],
  },
  {
    id: '234567890123456789',
    name: "Rinz Gaming Hub",
    icon: null,
    memberCount: 342,
    botPresent: true,
    voiceChannel: '876543210987654321',
    voiceChannelName: '🎮 Gaming VC',
    mode247: false,
    isPlaying: false,
    currentTrack: null,
  },
  {
    id: '345678901234567890',
    name: 'Chill Vibes Community',
    icon: null,
    memberCount: 89,
    botPresent: true,
    voiceChannel: null,
    voiceChannelName: null,
    mode247: false,
    isPlaying: false,
    currentTrack: null,
  },
  {
    id: '456789012345678901',
    name: 'Dev Zone',
    icon: null,
    memberCount: 56,
    botPresent: false,
    voiceChannel: null,
    voiceChannelName: null,
    mode247: false,
    isPlaying: false,
    currentTrack: null,
  },
];

export const MOCK_BOT_STATS: BotStats = {
  uptime: 259200, // 3 days
  guilds: 3,
  activeVoice: 2,
  tracksPlayed: 1842,
  cpuUsage: 12.4,
  memoryUsage: 145,
  memoryTotal: 512,
  ping: 47,
  status: 'online',
};

export const MOCK_VOICE_CHANNELS: VoiceChannel[] = [
  { id: '1', name: '🎵 Music Lounge', members: 4 },
  { id: '2', name: '🎮 Gaming VC', members: 2 },
  { id: '3', name: '📻 Radio Zone', members: 0 },
  { id: '4', name: '🔇 AFK', members: 1 },
];

export const MOCK_USER = {
  id: '111222333444555666',
  username: 'Deniz',
  discriminator: '0001',
  avatar: null,
  email: 'deniz@example.com',
};
